Solarized Look & Feel for Netbeans
==================================
Marco Herrn <marco@mherrn.de>
2018-03-17
:notoc:
:homepage: https://github.com/hupfdule/solarized-laf-netbeans
:solarized-homepage: http://ethanschoonover.com/solarized
:solarized-colorscheme-homepage: https://github.com/hupfdule/solarized-netbeans-colorscheme
:download-page: https://github.com/hupfdule/solarized-laf-netbeans/releases
:source-highlighter: prettify
:version: 1.0.0-SNAPSHOT

Netbeans Look & Feel inspired by the
{solarized-homepage}[Solarized Colorscheme for Vim].

This Look & Feel is intended to be used together with the
{solarized-colorscheme-homepage}[Solarized Colorscheme for Netbeans].

WARNING: This Look & Feel is still a work in progress and not in a usable
state yet.


Installation
------------

1. Get the current release from the {download-page}[Download page].
2. In Netbeans call "Tools" / "Plugins" / "Downloaded" and press the Button
   "Add Plugins…"
3. Select the nbm-file of this Look & Feel.
4. Press the Button "Install…"


Variants
--------

This Look & Feel currently only supports the light version. It is not an
exact copy of the original Solarized colorscheme, but uses some derivations.


License
-------

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
of the Software, and to permit persons to whom the Software is furnished to do
so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
